// Autogenerated API structures for: AWS Network Firewall

import * as cmnP from "../../encoding/common.ts";

// refs: 1 - tags: named, input
export interface AssociateFirewallPolicyRequest {
  UpdateToken?: string | null;
  FirewallArn?: string | null;
  FirewallName?: string | null;
  FirewallPolicyArn: string;
}

// refs: 1 - tags: named, input
export interface AssociateSubnetsRequest {
  UpdateToken?: string | null;
  FirewallArn?: string | null;
  FirewallName?: string | null;
  SubnetMappings: SubnetMapping[];
}

// refs: 1 - tags: named, input
export interface CreateFirewallRequest {
  FirewallName: string;
  FirewallPolicyArn: string;
  VpcId: string;
  SubnetMappings: SubnetMapping[];
  DeleteProtection?: boolean | null;
  SubnetChangeProtection?: boolean | null;
  FirewallPolicyChangeProtection?: boolean | null;
  Description?: string | null;
  Tags?: Tag[] | null;
}

// refs: 1 - tags: named, input
export interface CreateFirewallPolicyRequest {
  FirewallPolicyName: string;
  FirewallPolicy: FirewallPolicy;
  Description?: string | null;
  Tags?: Tag[] | null;
  DryRun?: boolean | null;
}

// refs: 1 - tags: named, input
export interface CreateRuleGroupRequest {
  RuleGroupName: string;
  RuleGroup?: RuleGroup | null;
  Rules?: string | null;
  Type: RuleGroupType;
  Description?: string | null;
  Capacity: number;
  Tags?: Tag[] | null;
  DryRun?: boolean | null;
}

// refs: 1 - tags: named, input
export interface DeleteFirewallRequest {
  FirewallName?: string | null;
  FirewallArn?: string | null;
}

// refs: 1 - tags: named, input
export interface DeleteFirewallPolicyRequest {
  FirewallPolicyName?: string | null;
  FirewallPolicyArn?: string | null;
}

// refs: 1 - tags: named, input
export interface DeleteResourcePolicyRequest {
  ResourceArn: string;
}

// refs: 1 - tags: named, input
export interface DeleteRuleGroupRequest {
  RuleGroupName?: string | null;
  RuleGroupArn?: string | null;
  Type?: RuleGroupType | null;
}

// refs: 1 - tags: named, input
export interface DescribeFirewallRequest {
  FirewallName?: string | null;
  FirewallArn?: string | null;
}

// refs: 1 - tags: named, input
export interface DescribeFirewallPolicyRequest {
  FirewallPolicyName?: string | null;
  FirewallPolicyArn?: string | null;
}

// refs: 1 - tags: named, input
export interface DescribeLoggingConfigurationRequest {
  FirewallArn?: string | null;
  FirewallName?: string | null;
}

// refs: 1 - tags: named, input
export interface DescribeResourcePolicyRequest {
  ResourceArn: string;
}

// refs: 1 - tags: named, input
export interface DescribeRuleGroupRequest {
  RuleGroupName?: string | null;
  RuleGroupArn?: string | null;
  Type?: RuleGroupType | null;
}

// refs: 1 - tags: named, input
export interface DisassociateSubnetsRequest {
  UpdateToken?: string | null;
  FirewallArn?: string | null;
  FirewallName?: string | null;
  SubnetIds: string[];
}

// refs: 1 - tags: named, input
export interface ListFirewallPoliciesRequest {
  NextToken?: string | null;
  MaxResults?: number | null;
}

// refs: 1 - tags: named, input
export interface ListFirewallsRequest {
  NextToken?: string | null;
  VpcIds?: string[] | null;
  MaxResults?: number | null;
}

// refs: 1 - tags: named, input
export interface ListRuleGroupsRequest {
  NextToken?: string | null;
  MaxResults?: number | null;
}

// refs: 1 - tags: named, input
export interface ListTagsForResourceRequest {
  NextToken?: string | null;
  MaxResults?: number | null;
  ResourceArn: string;
}

// refs: 1 - tags: named, input
export interface PutResourcePolicyRequest {
  ResourceArn: string;
  Policy: string;
}

// refs: 1 - tags: named, input
export interface TagResourceRequest {
  ResourceArn: string;
  Tags: Tag[];
}

// refs: 1 - tags: named, input
export interface UntagResourceRequest {
  ResourceArn: string;
  TagKeys: string[];
}

// refs: 1 - tags: named, input
export interface UpdateFirewallDeleteProtectionRequest {
  UpdateToken?: string | null;
  FirewallArn?: string | null;
  FirewallName?: string | null;
  DeleteProtection: boolean;
}

// refs: 1 - tags: named, input
export interface UpdateFirewallDescriptionRequest {
  UpdateToken?: string | null;
  FirewallArn?: string | null;
  FirewallName?: string | null;
  Description?: string | null;
}

// refs: 1 - tags: named, input
export interface UpdateFirewallPolicyRequest {
  UpdateToken: string;
  FirewallPolicyArn?: string | null;
  FirewallPolicyName?: string | null;
  FirewallPolicy: FirewallPolicy;
  Description?: string | null;
  DryRun?: boolean | null;
}

// refs: 1 - tags: named, input
export interface UpdateFirewallPolicyChangeProtectionRequest {
  UpdateToken?: string | null;
  FirewallArn?: string | null;
  FirewallName?: string | null;
  FirewallPolicyChangeProtection: boolean;
}

// refs: 1 - tags: named, input
export interface UpdateLoggingConfigurationRequest {
  FirewallArn?: string | null;
  FirewallName?: string | null;
  LoggingConfiguration?: LoggingConfiguration | null;
}

// refs: 1 - tags: named, input
export interface UpdateRuleGroupRequest {
  UpdateToken: string;
  RuleGroupArn?: string | null;
  RuleGroupName?: string | null;
  RuleGroup?: RuleGroup | null;
  Rules?: string | null;
  Type?: RuleGroupType | null;
  Description?: string | null;
  DryRun?: boolean | null;
}

// refs: 1 - tags: named, input
export interface UpdateSubnetChangeProtectionRequest {
  UpdateToken?: string | null;
  FirewallArn?: string | null;
  FirewallName?: string | null;
  SubnetChangeProtection: boolean;
}

// refs: 1 - tags: named, output
export interface AssociateFirewallPolicyResponse {
  FirewallArn?: string | null;
  FirewallName?: string | null;
  FirewallPolicyArn?: string | null;
  UpdateToken?: string | null;
}

// refs: 1 - tags: named, output
export interface AssociateSubnetsResponse {
  FirewallArn?: string | null;
  FirewallName?: string | null;
  SubnetMappings?: SubnetMapping[] | null;
  UpdateToken?: string | null;
}

// refs: 1 - tags: named, output
export interface CreateFirewallResponse {
  Firewall?: Firewall | null;
  FirewallStatus?: FirewallStatus | null;
}

// refs: 1 - tags: named, output
export interface CreateFirewallPolicyResponse {
  UpdateToken: string;
  FirewallPolicyResponse: FirewallPolicyResponse;
}

// refs: 1 - tags: named, output
export interface CreateRuleGroupResponse {
  UpdateToken: string;
  RuleGroupResponse: RuleGroupResponse;
}

// refs: 1 - tags: named, output
export interface DeleteFirewallResponse {
  Firewall?: Firewall | null;
  FirewallStatus?: FirewallStatus | null;
}

// refs: 1 - tags: named, output
export interface DeleteFirewallPolicyResponse {
  FirewallPolicyResponse: FirewallPolicyResponse;
}

// refs: 1 - tags: named, output
export interface DeleteResourcePolicyResponse {
}

// refs: 1 - tags: named, output
export interface DeleteRuleGroupResponse {
  RuleGroupResponse: RuleGroupResponse;
}

// refs: 1 - tags: named, output
export interface DescribeFirewallResponse {
  UpdateToken?: string | null;
  Firewall?: Firewall | null;
  FirewallStatus?: FirewallStatus | null;
}

// refs: 1 - tags: named, output
export interface DescribeFirewallPolicyResponse {
  UpdateToken: string;
  FirewallPolicyResponse: FirewallPolicyResponse;
  FirewallPolicy?: FirewallPolicy | null;
}

// refs: 1 - tags: named, output
export interface DescribeLoggingConfigurationResponse {
  FirewallArn?: string | null;
  LoggingConfiguration?: LoggingConfiguration | null;
}

// refs: 1 - tags: named, output
export interface DescribeResourcePolicyResponse {
  Policy?: string | null;
}

// refs: 1 - tags: named, output
export interface DescribeRuleGroupResponse {
  UpdateToken: string;
  RuleGroup?: RuleGroup | null;
  RuleGroupResponse: RuleGroupResponse;
}

// refs: 1 - tags: named, output
export interface DisassociateSubnetsResponse {
  FirewallArn?: string | null;
  FirewallName?: string | null;
  SubnetMappings?: SubnetMapping[] | null;
  UpdateToken?: string | null;
}

// refs: 1 - tags: named, output
export interface ListFirewallPoliciesResponse {
  NextToken?: string | null;
  FirewallPolicies?: FirewallPolicyMetadata[] | null;
}

// refs: 1 - tags: named, output
export interface ListFirewallsResponse {
  NextToken?: string | null;
  Firewalls?: FirewallMetadata[] | null;
}

// refs: 1 - tags: named, output
export interface ListRuleGroupsResponse {
  NextToken?: string | null;
  RuleGroups?: RuleGroupMetadata[] | null;
}

// refs: 1 - tags: named, output
export interface ListTagsForResourceResponse {
  NextToken?: string | null;
  Tags?: Tag[] | null;
}

// refs: 1 - tags: named, output
export interface PutResourcePolicyResponse {
}

// refs: 1 - tags: named, output
export interface TagResourceResponse {
}

// refs: 1 - tags: named, output
export interface UntagResourceResponse {
}

// refs: 1 - tags: named, output
export interface UpdateFirewallDeleteProtectionResponse {
  FirewallArn?: string | null;
  FirewallName?: string | null;
  DeleteProtection?: boolean | null;
  UpdateToken?: string | null;
}

// refs: 1 - tags: named, output
export interface UpdateFirewallDescriptionResponse {
  FirewallArn?: string | null;
  FirewallName?: string | null;
  Description?: string | null;
  UpdateToken?: string | null;
}

// refs: 1 - tags: named, output
export interface UpdateFirewallPolicyResponse {
  UpdateToken: string;
  FirewallPolicyResponse: FirewallPolicyResponse;
}

// refs: 1 - tags: named, output
export interface UpdateFirewallPolicyChangeProtectionResponse {
  UpdateToken?: string | null;
  FirewallArn?: string | null;
  FirewallName?: string | null;
  FirewallPolicyChangeProtection?: boolean | null;
}

// refs: 1 - tags: named, output
export interface UpdateLoggingConfigurationResponse {
  FirewallArn?: string | null;
  FirewallName?: string | null;
  LoggingConfiguration?: LoggingConfiguration | null;
}

// refs: 1 - tags: named, output
export interface UpdateRuleGroupResponse {
  UpdateToken: string;
  RuleGroupResponse: RuleGroupResponse;
}

// refs: 1 - tags: named, output
export interface UpdateSubnetChangeProtectionResponse {
  UpdateToken?: string | null;
  FirewallArn?: string | null;
  FirewallName?: string | null;
  SubnetChangeProtection?: boolean | null;
}

// refs: 7 - tags: input, named, interface, output
export interface SubnetMapping {
  SubnetId: string;
}

// refs: 16 - tags: input, named, interface, output
export interface Tag {
  Key: string;
  Value: string;
}

// refs: 3 - tags: input, named, interface, output
export interface FirewallPolicy {
  StatelessRuleGroupReferences?: StatelessRuleGroupReference[] | null;
  StatelessDefaultActions: string[];
  StatelessFragmentDefaultActions: string[];
  StatelessCustomActions?: CustomAction[] | null;
  StatefulRuleGroupReferences?: StatefulRuleGroupReference[] | null;
}

// refs: 3 - tags: input, named, interface, output
export interface StatelessRuleGroupReference {
  ResourceArn: string;
  Priority: number;
}

// refs: 6 - tags: input, named, interface, output
export interface CustomAction {
  ActionName: string;
  ActionDefinition: ActionDefinition;
}

// refs: 6 - tags: input, named, interface, output
export interface ActionDefinition {
  PublishMetricAction?: PublishMetricAction | null;
}

// refs: 6 - tags: input, named, interface, output
export interface PublishMetricAction {
  Dimensions: Dimension[];
}

// refs: 6 - tags: input, named, interface, output
export interface Dimension {
  Value: string;
}

// refs: 3 - tags: input, named, interface, output
export interface StatefulRuleGroupReference {
  ResourceArn: string;
}

// refs: 3 - tags: input, named, interface, output
export interface RuleGroup {
  RuleVariables?: RuleVariables | null;
  RulesSource: RulesSource;
}

// refs: 3 - tags: input, named, interface, output
export interface RuleVariables {
  IPSets?: { [key: string]: IPSet | null | undefined } | null;
  PortSets?: { [key: string]: PortSet | null | undefined } | null;
}

// refs: 3 - tags: input, named, interface, output
export interface IPSet {
  Definition: string[];
}

// refs: 3 - tags: input, named, interface, output
export interface PortSet {
  Definition?: string[] | null;
}

// refs: 3 - tags: input, named, interface, output
export interface RulesSource {
  RulesString?: string | null;
  RulesSourceList?: RulesSourceList | null;
  StatefulRules?: StatefulRule[] | null;
  StatelessRulesAndCustomActions?: StatelessRulesAndCustomActions | null;
}

// refs: 3 - tags: input, named, interface, output
export interface RulesSourceList {
  Targets: string[];
  TargetTypes: TargetType[];
  GeneratedRulesType: GeneratedRulesType;
}

// refs: 3 - tags: input, named, enum, output
export type TargetType =
| "TLS_SNI"
| "HTTP_HOST"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: input, named, enum, output
export type GeneratedRulesType =
| "ALLOWLIST"
| "DENYLIST"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: input, named, interface, output
export interface StatefulRule {
  Action: StatefulAction;
  Header: Header;
  RuleOptions: RuleOption[];
}

// refs: 3 - tags: input, named, enum, output
export type StatefulAction =
| "PASS"
| "DROP"
| "ALERT"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: input, named, interface, output
export interface Header {
  Protocol: StatefulRuleProtocol;
  Source: string;
  SourcePort: string;
  Direction: StatefulRuleDirection;
  Destination: string;
  DestinationPort: string;
}

// refs: 3 - tags: input, named, enum, output
export type StatefulRuleProtocol =
| "IP"
| "TCP"
| "UDP"
| "ICMP"
| "HTTP"
| "FTP"
| "TLS"
| "SMB"
| "DNS"
| "DCERPC"
| "SSH"
| "SMTP"
| "IMAP"
| "MSN"
| "KRB5"
| "IKEV2"
| "TFTP"
| "NTP"
| "DHCP"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: input, named, enum, output
export type StatefulRuleDirection =
| "FORWARD"
| "ANY"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: input, named, interface, output
export interface RuleOption {
  Keyword: string;
  Settings?: string[] | null;
}

// refs: 3 - tags: input, named, interface, output
export interface StatelessRulesAndCustomActions {
  StatelessRules: StatelessRule[];
  CustomActions?: CustomAction[] | null;
}

// refs: 3 - tags: input, named, interface, output
export interface StatelessRule {
  RuleDefinition: RuleDefinition;
  Priority: number;
}

// refs: 3 - tags: input, named, interface, output
export interface RuleDefinition {
  MatchAttributes: MatchAttributes;
  Actions: string[];
}

// refs: 3 - tags: input, named, interface, output
export interface MatchAttributes {
  Sources?: Address[] | null;
  Destinations?: Address[] | null;
  SourcePorts?: PortRange[] | null;
  DestinationPorts?: PortRange[] | null;
  Protocols?: number[] | null;
  TCPFlags?: TCPFlagField[] | null;
}

// refs: 6 - tags: input, named, interface, output
export interface Address {
  AddressDefinition: string;
}

// refs: 6 - tags: input, named, interface, output
export interface PortRange {
  FromPort: number;
  ToPort: number;
}

// refs: 3 - tags: input, named, interface, output
export interface TCPFlagField {
  Flags: TCPFlag[];
  Masks?: TCPFlag[] | null;
}

// refs: 6 - tags: input, named, enum, output
export type TCPFlag =
| "FIN"
| "SYN"
| "RST"
| "PSH"
| "ACK"
| "URG"
| "ECE"
| "CWR"
| cmnP.UnexpectedEnumValue;

// refs: 8 - tags: input, named, enum, output
export type RuleGroupType =
| "STATELESS"
| "STATEFUL"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: input, named, interface, output
export interface LoggingConfiguration {
  LogDestinationConfigs: LogDestinationConfig[];
}

// refs: 3 - tags: input, named, interface, output
export interface LogDestinationConfig {
  LogType: LogType;
  LogDestinationType: LogDestinationType;
  LogDestination: { [key: string]: string | null | undefined };
}

// refs: 3 - tags: input, named, enum, output
export type LogType =
| "ALERT"
| "FLOW"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: input, named, enum, output
export type LogDestinationType =
| "S3"
| "CloudWatchLogs"
| "KinesisDataFirehose"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: output, named, interface
export interface Firewall {
  FirewallName?: string | null;
  FirewallArn?: string | null;
  FirewallPolicyArn: string;
  VpcId: string;
  SubnetMappings: SubnetMapping[];
  DeleteProtection?: boolean | null;
  SubnetChangeProtection?: boolean | null;
  FirewallPolicyChangeProtection?: boolean | null;
  Description?: string | null;
  FirewallId: string;
  Tags?: Tag[] | null;
}

// refs: 3 - tags: output, named, interface
export interface FirewallStatus {
  Status: FirewallStatusValue;
  ConfigurationSyncStateSummary: ConfigurationSyncState;
  SyncStates?: { [key: string]: SyncState | null | undefined } | null;
}

// refs: 3 - tags: output, named, enum
export type FirewallStatusValue =
| "PROVISIONING"
| "DELETING"
| "READY"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: output, named, enum
export type ConfigurationSyncState =
| "PENDING"
| "IN_SYNC"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: output, named, interface
export interface SyncState {
  Attachment?: Attachment | null;
  Config?: { [key: string]: PerObjectStatus | null | undefined } | null;
}

// refs: 3 - tags: output, named, interface
export interface Attachment {
  SubnetId?: string | null;
  EndpointId?: string | null;
  Status?: AttachmentStatus | null;
}

// refs: 3 - tags: output, named, enum
export type AttachmentStatus =
| "CREATING"
| "DELETING"
| "SCALING"
| "READY"
| cmnP.UnexpectedEnumValue;

// refs: 3 - tags: output, named, interface
export interface PerObjectStatus {
  SyncStatus?: PerObjectSyncStatus | null;
}

// refs: 3 - tags: output, named, enum
export type PerObjectSyncStatus =
| "PENDING"
| "IN_SYNC"
| cmnP.UnexpectedEnumValue;

// refs: 4 - tags: output, named, interface
export interface FirewallPolicyResponse {
  FirewallPolicyName: string;
  FirewallPolicyArn: string;
  FirewallPolicyId: string;
  Description?: string | null;
  FirewallPolicyStatus?: ResourceStatus | null;
  Tags?: Tag[] | null;
}

// refs: 8 - tags: output, named, enum
export type ResourceStatus =
| "ACTIVE"
| "DELETING"
| cmnP.UnexpectedEnumValue;

// refs: 4 - tags: output, named, interface
export interface RuleGroupResponse {
  RuleGroupArn: string;
  RuleGroupName: string;
  RuleGroupId: string;
  Description?: string | null;
  Type?: RuleGroupType | null;
  Capacity?: number | null;
  RuleGroupStatus?: ResourceStatus | null;
  Tags?: Tag[] | null;
}

// refs: 1 - tags: output, named, interface
export interface FirewallPolicyMetadata {
  Name?: string | null;
  Arn?: string | null;
}

// refs: 1 - tags: output, named, interface
export interface FirewallMetadata {
  FirewallName?: string | null;
  FirewallArn?: string | null;
}

// refs: 1 - tags: output, named, interface
export interface RuleGroupMetadata {
  Name?: string | null;
  Arn?: string | null;
}
