// Autogenerated API structures for: Amazon Prometheus Service

import * as cmnP from "../../encoding/common.ts";

// refs: 1 - tags: named, input
export interface CreateWorkspaceRequest {
  alias?: string | null;
  clientToken?: string | null;
}

// refs: 1 - tags: named, input
export interface DeleteWorkspaceRequest {
  clientToken?: string | null;
  workspaceId: string;
}

// refs: 1 - tags: named, input
export interface DescribeWorkspaceRequest {
  workspaceId: string;
}

// refs: 1 - tags: named, input
export interface ListWorkspacesRequest {
  alias?: string | null;
  maxResults?: number | null;
  nextToken?: string | null;
}

// refs: 1 - tags: named, input
export interface UpdateWorkspaceAliasRequest {
  alias?: string | null;
  clientToken?: string | null;
  workspaceId: string;
}

// refs: 1 - tags: named, output
export interface CreateWorkspaceResponse {
  arn: string;
  status: WorkspaceStatus;
  workspaceId: string;
}

// refs: 1 - tags: named, output
export interface DescribeWorkspaceResponse {
  workspace: WorkspaceDescription;
}

// refs: 1 - tags: named, output
export interface ListWorkspacesResponse {
  nextToken?: string | null;
  workspaces: WorkspaceSummary[];
}

// refs: 3 - tags: output, named, interface
export interface WorkspaceStatus {
  statusCode: WorkspaceStatusCode;
}

// refs: 3 - tags: output, named, enum
export type WorkspaceStatusCode =
| "CREATING"
| "ACTIVE"
| "UPDATING"
| "DELETING"
| "CREATION_FAILED"
| cmnP.UnexpectedEnumValue;

// refs: 1 - tags: output, named, interface
export interface WorkspaceDescription {
  alias?: string | null;
  arn: string;
  createdAt: Date | number;
  prometheusEndpoint?: string | null;
  status: WorkspaceStatus;
  workspaceId: string;
}

// refs: 1 - tags: output, named, interface
export interface WorkspaceSummary {
  alias?: string | null;
  arn: string;
  createdAt: Date | number;
  status: WorkspaceStatus;
  workspaceId: string;
}
