// Autogenerated API client for: Amazon WorkMail Message Flow

interface RequestConfig {
  abortSignal?: AbortSignal;
}

export * from "./structs.ts";
import * as client from "../../client/common.ts";
import * as cmnP from "../../encoding/common.ts";
import * as jsonP from "../../encoding/json.ts";
import type * as s from "./structs.ts";

export default class WorkMailMessageFlow {
  #client: client.ServiceClient;
  constructor(apiFactory: client.ApiFactory) {
    this.#client = apiFactory.buildServiceClient(WorkMailMessageFlow.ApiMetadata);
  }

  static ApiMetadata: client.ApiMetadata = {
    "apiVersion": "2019-05-01",
    "endpointPrefix": "workmailmessageflow",
    "jsonVersion": "1.1",
    "protocol": "rest-json",
    "serviceFullName": "Amazon WorkMail Message Flow",
    "serviceId": "WorkMailMessageFlow",
    "signatureVersion": "v4",
    "uid": "workmailmessageflow-2019-05-01"
  };

  async getRawMessageContent(
    {abortSignal, ...params}: RequestConfig & s.GetRawMessageContentRequest,
  ): Promise<s.GetRawMessageContentResponse> {

    const resp = await this.#client.performRequest({
      abortSignal,
      action: "GetRawMessageContent",
      method: "GET",
      requestUri: cmnP.encodePath`/messages/${params["messageId"]}`,
    });
    return {
      messageContent: await resp.text(), // TODO: maybe allow proper body streaming,
    };
  }

  async putRawMessageContent(
    {abortSignal, ...params}: RequestConfig & s.PutRawMessageContentRequest,
  ): Promise<void> {
    const body: jsonP.JSONObject = {
      content: fromRawMessageContent(params["content"]),
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "PutRawMessageContent",
      requestUri: cmnP.encodePath`/messages/${params["messageId"]}`,
    });
    await resp.text();
  }

}

function fromRawMessageContent(input?: s.RawMessageContent | null): jsonP.JSONValue {
  if (!input) return input;
  return {
    s3Reference: fromS3Reference(input["s3Reference"]),
  }
}

function fromS3Reference(input?: s.S3Reference | null): jsonP.JSONValue {
  if (!input) return input;
  return {
    bucket: input["bucket"],
    key: input["key"],
    objectVersion: input["objectVersion"],
  }
}
