// Autogenerated API client for: AWS Shield

import type { ServiceClient, ApiFactory, ApiMetadata } from '../../client/common.ts';
interface RequestConfig {
  abortSignal?: AbortSignal;
}

import * as cmnP from "../../encoding/common.ts";
import * as jsonP from "../../encoding/json.ts";

export default class Shield {
  #client: ServiceClient;
  constructor(apiFactory: ApiFactory) {
    this.#client = apiFactory.buildServiceClient(Shield.ApiMetadata);
  }

  static ApiMetadata: ApiMetadata = {
    "apiVersion": "2016-06-02",
    "endpointPrefix": "shield",
    "jsonVersion": "1.1",
    "protocol": "json",
    "serviceAbbreviation": "AWS Shield",
    "serviceFullName": "AWS Shield",
    "serviceId": "Shield",
    "signatureVersion": "v4",
    "targetPrefix": "AWSShield_20160616",
    "uid": "shield-2016-06-02"
  };

  async associateDRTLogBucket(
    {abortSignal, ...params}: RequestConfig & AssociateDRTLogBucketRequest,
  ): Promise<AssociateDRTLogBucketResponse> {
    const body: jsonP.JSONObject = {
      LogBucket: params["LogBucket"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "AssociateDRTLogBucket",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async associateDRTRole(
    {abortSignal, ...params}: RequestConfig & AssociateDRTRoleRequest,
  ): Promise<AssociateDRTRoleResponse> {
    const body: jsonP.JSONObject = {
      RoleArn: params["RoleArn"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "AssociateDRTRole",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async associateHealthCheck(
    {abortSignal, ...params}: RequestConfig & AssociateHealthCheckRequest,
  ): Promise<AssociateHealthCheckResponse> {
    const body: jsonP.JSONObject = {
      ProtectionId: params["ProtectionId"],
      HealthCheckArn: params["HealthCheckArn"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "AssociateHealthCheck",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async associateProactiveEngagementDetails(
    {abortSignal, ...params}: RequestConfig & AssociateProactiveEngagementDetailsRequest,
  ): Promise<AssociateProactiveEngagementDetailsResponse> {
    const body: jsonP.JSONObject = {
      EmergencyContactList: params["EmergencyContactList"]?.map(x => fromEmergencyContact(x)),
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "AssociateProactiveEngagementDetails",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async createProtection(
    {abortSignal, ...params}: RequestConfig & CreateProtectionRequest,
  ): Promise<CreateProtectionResponse> {
    const body: jsonP.JSONObject = {
      Name: params["Name"],
      ResourceArn: params["ResourceArn"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "CreateProtection",
    });
    return jsonP.readObj({
      required: {},
      optional: {
        "ProtectionId": "s",
      },
    }, await resp.json());
  }

  async createSubscription(
    {abortSignal, ...params}: RequestConfig & CreateSubscriptionRequest = {},
  ): Promise<CreateSubscriptionResponse> {
    const body: jsonP.JSONObject = {
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "CreateSubscription",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async deleteProtection(
    {abortSignal, ...params}: RequestConfig & DeleteProtectionRequest,
  ): Promise<DeleteProtectionResponse> {
    const body: jsonP.JSONObject = {
      ProtectionId: params["ProtectionId"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DeleteProtection",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async deleteSubscription(
    {abortSignal, ...params}: RequestConfig & DeleteSubscriptionRequest = {},
  ): Promise<DeleteSubscriptionResponse> {
    const body: jsonP.JSONObject = {
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DeleteSubscription",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async describeAttack(
    {abortSignal, ...params}: RequestConfig & DescribeAttackRequest,
  ): Promise<DescribeAttackResponse> {
    const body: jsonP.JSONObject = {
      AttackId: params["AttackId"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DescribeAttack",
    });
    return jsonP.readObj({
      required: {},
      optional: {
        "Attack": toAttackDetail,
      },
    }, await resp.json());
  }

  async describeDRTAccess(
    {abortSignal, ...params}: RequestConfig & DescribeDRTAccessRequest = {},
  ): Promise<DescribeDRTAccessResponse> {
    const body: jsonP.JSONObject = {
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DescribeDRTAccess",
    });
    return jsonP.readObj({
      required: {},
      optional: {
        "RoleArn": "s",
        "LogBucketList": ["s"],
      },
    }, await resp.json());
  }

  async describeEmergencyContactSettings(
    {abortSignal, ...params}: RequestConfig & DescribeEmergencyContactSettingsRequest = {},
  ): Promise<DescribeEmergencyContactSettingsResponse> {
    const body: jsonP.JSONObject = {
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DescribeEmergencyContactSettings",
    });
    return jsonP.readObj({
      required: {},
      optional: {
        "EmergencyContactList": [toEmergencyContact],
      },
    }, await resp.json());
  }

  async describeProtection(
    {abortSignal, ...params}: RequestConfig & DescribeProtectionRequest = {},
  ): Promise<DescribeProtectionResponse> {
    const body: jsonP.JSONObject = {
      ProtectionId: params["ProtectionId"],
      ResourceArn: params["ResourceArn"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DescribeProtection",
    });
    return jsonP.readObj({
      required: {},
      optional: {
        "Protection": toProtection,
      },
    }, await resp.json());
  }

  async describeSubscription(
    {abortSignal, ...params}: RequestConfig & DescribeSubscriptionRequest = {},
  ): Promise<DescribeSubscriptionResponse> {
    const body: jsonP.JSONObject = {
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DescribeSubscription",
    });
    return jsonP.readObj({
      required: {},
      optional: {
        "Subscription": toSubscription,
      },
    }, await resp.json());
  }

  async disableProactiveEngagement(
    {abortSignal, ...params}: RequestConfig & DisableProactiveEngagementRequest = {},
  ): Promise<DisableProactiveEngagementResponse> {
    const body: jsonP.JSONObject = {
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DisableProactiveEngagement",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async disassociateDRTLogBucket(
    {abortSignal, ...params}: RequestConfig & DisassociateDRTLogBucketRequest,
  ): Promise<DisassociateDRTLogBucketResponse> {
    const body: jsonP.JSONObject = {
      LogBucket: params["LogBucket"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DisassociateDRTLogBucket",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async disassociateDRTRole(
    {abortSignal, ...params}: RequestConfig & DisassociateDRTRoleRequest = {},
  ): Promise<DisassociateDRTRoleResponse> {
    const body: jsonP.JSONObject = {
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DisassociateDRTRole",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async disassociateHealthCheck(
    {abortSignal, ...params}: RequestConfig & DisassociateHealthCheckRequest,
  ): Promise<DisassociateHealthCheckResponse> {
    const body: jsonP.JSONObject = {
      ProtectionId: params["ProtectionId"],
      HealthCheckArn: params["HealthCheckArn"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "DisassociateHealthCheck",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async enableProactiveEngagement(
    {abortSignal, ...params}: RequestConfig & EnableProactiveEngagementRequest = {},
  ): Promise<EnableProactiveEngagementResponse> {
    const body: jsonP.JSONObject = {
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "EnableProactiveEngagement",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async getSubscriptionState(
    {abortSignal, ...params}: RequestConfig & GetSubscriptionStateRequest = {},
  ): Promise<GetSubscriptionStateResponse> {
    const body: jsonP.JSONObject = {
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "GetSubscriptionState",
    });
    return jsonP.readObj({
      required: {
        "SubscriptionState": (x: jsonP.JSONValue) => cmnP.readEnum<SubscriptionState>(x),
      },
      optional: {},
    }, await resp.json());
  }

  async listAttacks(
    {abortSignal, ...params}: RequestConfig & ListAttacksRequest = {},
  ): Promise<ListAttacksResponse> {
    const body: jsonP.JSONObject = {
      ResourceArns: params["ResourceArns"],
      StartTime: fromTimeRange(params["StartTime"]),
      EndTime: fromTimeRange(params["EndTime"]),
      NextToken: params["NextToken"],
      MaxResults: params["MaxResults"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "ListAttacks",
    });
    return jsonP.readObj({
      required: {},
      optional: {
        "AttackSummaries": [toAttackSummary],
        "NextToken": "s",
      },
    }, await resp.json());
  }

  async listProtections(
    {abortSignal, ...params}: RequestConfig & ListProtectionsRequest = {},
  ): Promise<ListProtectionsResponse> {
    const body: jsonP.JSONObject = {
      NextToken: params["NextToken"],
      MaxResults: params["MaxResults"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "ListProtections",
    });
    return jsonP.readObj({
      required: {},
      optional: {
        "Protections": [toProtection],
        "NextToken": "s",
      },
    }, await resp.json());
  }

  async updateEmergencyContactSettings(
    {abortSignal, ...params}: RequestConfig & UpdateEmergencyContactSettingsRequest = {},
  ): Promise<UpdateEmergencyContactSettingsResponse> {
    const body: jsonP.JSONObject = {
      EmergencyContactList: params["EmergencyContactList"]?.map(x => fromEmergencyContact(x)),
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "UpdateEmergencyContactSettings",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

  async updateSubscription(
    {abortSignal, ...params}: RequestConfig & UpdateSubscriptionRequest = {},
  ): Promise<UpdateSubscriptionResponse> {
    const body: jsonP.JSONObject = {
      AutoRenew: params["AutoRenew"],
    };
    const resp = await this.#client.performRequest({
      abortSignal, body,
      action: "UpdateSubscription",
    });
    return jsonP.readObj({
      required: {},
      optional: {},
    }, await resp.json());
  }

}

// refs: 1 - tags: named, input
export interface AssociateDRTLogBucketRequest {
  LogBucket: string;
}

// refs: 1 - tags: named, input
export interface AssociateDRTRoleRequest {
  RoleArn: string;
}

// refs: 1 - tags: named, input
export interface AssociateHealthCheckRequest {
  ProtectionId: string;
  HealthCheckArn: string;
}

// refs: 1 - tags: named, input
export interface AssociateProactiveEngagementDetailsRequest {
  EmergencyContactList: EmergencyContact[];
}

// refs: 1 - tags: named, input
export interface CreateProtectionRequest {
  Name: string;
  ResourceArn: string;
}

// refs: 1 - tags: named, input
export interface CreateSubscriptionRequest {
}

// refs: 1 - tags: named, input
export interface DeleteProtectionRequest {
  ProtectionId: string;
}

// refs: 1 - tags: named, input
export interface DeleteSubscriptionRequest {
}

// refs: 1 - tags: named, input
export interface DescribeAttackRequest {
  AttackId: string;
}

// refs: 1 - tags: named, input
export interface DescribeDRTAccessRequest {
}

// refs: 1 - tags: named, input
export interface DescribeEmergencyContactSettingsRequest {
}

// refs: 1 - tags: named, input
export interface DescribeProtectionRequest {
  ProtectionId?: string | null;
  ResourceArn?: string | null;
}

// refs: 1 - tags: named, input
export interface DescribeSubscriptionRequest {
}

// refs: 1 - tags: named, input
export interface DisableProactiveEngagementRequest {
}

// refs: 1 - tags: named, input
export interface DisassociateDRTLogBucketRequest {
  LogBucket: string;
}

// refs: 1 - tags: named, input
export interface DisassociateDRTRoleRequest {
}

// refs: 1 - tags: named, input
export interface DisassociateHealthCheckRequest {
  ProtectionId: string;
  HealthCheckArn: string;
}

// refs: 1 - tags: named, input
export interface EnableProactiveEngagementRequest {
}

// refs: 1 - tags: named, input
export interface GetSubscriptionStateRequest {
}

// refs: 1 - tags: named, input
export interface ListAttacksRequest {
  ResourceArns?: string[] | null;
  StartTime?: TimeRange | null;
  EndTime?: TimeRange | null;
  NextToken?: string | null;
  MaxResults?: number | null;
}

// refs: 1 - tags: named, input
export interface ListProtectionsRequest {
  NextToken?: string | null;
  MaxResults?: number | null;
}

// refs: 1 - tags: named, input
export interface UpdateEmergencyContactSettingsRequest {
  EmergencyContactList?: EmergencyContact[] | null;
}

// refs: 1 - tags: named, input
export interface UpdateSubscriptionRequest {
  AutoRenew?: AutoRenew | null;
}

// refs: 1 - tags: named, output
export interface AssociateDRTLogBucketResponse {
}

// refs: 1 - tags: named, output
export interface AssociateDRTRoleResponse {
}

// refs: 1 - tags: named, output
export interface AssociateHealthCheckResponse {
}

// refs: 1 - tags: named, output
export interface AssociateProactiveEngagementDetailsResponse {
}

// refs: 1 - tags: named, output
export interface CreateProtectionResponse {
  ProtectionId?: string | null;
}

// refs: 1 - tags: named, output
export interface CreateSubscriptionResponse {
}

// refs: 1 - tags: named, output
export interface DeleteProtectionResponse {
}

// refs: 1 - tags: named, output
export interface DeleteSubscriptionResponse {
}

// refs: 1 - tags: named, output
export interface DescribeAttackResponse {
  Attack?: AttackDetail | null;
}

// refs: 1 - tags: named, output
export interface DescribeDRTAccessResponse {
  RoleArn?: string | null;
  LogBucketList?: string[] | null;
}

// refs: 1 - tags: named, output
export interface DescribeEmergencyContactSettingsResponse {
  EmergencyContactList?: EmergencyContact[] | null;
}

// refs: 1 - tags: named, output
export interface DescribeProtectionResponse {
  Protection?: Protection | null;
}

// refs: 1 - tags: named, output
export interface DescribeSubscriptionResponse {
  Subscription?: Subscription | null;
}

// refs: 1 - tags: named, output
export interface DisableProactiveEngagementResponse {
}

// refs: 1 - tags: named, output
export interface DisassociateDRTLogBucketResponse {
}

// refs: 1 - tags: named, output
export interface DisassociateDRTRoleResponse {
}

// refs: 1 - tags: named, output
export interface DisassociateHealthCheckResponse {
}

// refs: 1 - tags: named, output
export interface EnableProactiveEngagementResponse {
}

// refs: 1 - tags: named, output
export interface GetSubscriptionStateResponse {
  SubscriptionState: SubscriptionState;
}

// refs: 1 - tags: named, output
export interface ListAttacksResponse {
  AttackSummaries?: AttackSummary[] | null;
  NextToken?: string | null;
}

// refs: 1 - tags: named, output
export interface ListProtectionsResponse {
  Protections?: Protection[] | null;
  NextToken?: string | null;
}

// refs: 1 - tags: named, output
export interface UpdateEmergencyContactSettingsResponse {
}

// refs: 1 - tags: named, output
export interface UpdateSubscriptionResponse {
}

// refs: 3 - tags: input, named, interface, output
export interface EmergencyContact {
  EmailAddress: string;
  PhoneNumber?: string | null;
  ContactNotes?: string | null;
}
function fromEmergencyContact(input?: EmergencyContact | null): jsonP.JSONValue {
  if (!input) return input;
  return {
    EmailAddress: input["EmailAddress"],
    PhoneNumber: input["PhoneNumber"],
    ContactNotes: input["ContactNotes"],
  }
}
function toEmergencyContact(root: jsonP.JSONValue): EmergencyContact {
  return jsonP.readObj({
    required: {
      "EmailAddress": "s",
    },
    optional: {
      "PhoneNumber": "s",
      "ContactNotes": "s",
    },
  }, root);
}

// refs: 2 - tags: input, named, interface
export interface TimeRange {
  FromInclusive?: Date | number | null;
  ToExclusive?: Date | number | null;
}
function fromTimeRange(input?: TimeRange | null): jsonP.JSONValue {
  if (!input) return input;
  return {
    FromInclusive: jsonP.serializeDate_unixTimestamp(input["FromInclusive"]),
    ToExclusive: jsonP.serializeDate_unixTimestamp(input["ToExclusive"]),
  }
}

// refs: 2 - tags: input, named, enum, output
export type AutoRenew =
| "ENABLED"
| "DISABLED"
| cmnP.UnexpectedEnumValue;

// refs: 1 - tags: output, named, interface
export interface AttackDetail {
  AttackId?: string | null;
  ResourceArn?: string | null;
  SubResources?: SubResourceSummary[] | null;
  StartTime?: Date | number | null;
  EndTime?: Date | number | null;
  AttackCounters?: SummarizedCounter[] | null;
  AttackProperties?: AttackProperty[] | null;
  Mitigations?: Mitigation[] | null;
}
function toAttackDetail(root: jsonP.JSONValue): AttackDetail {
  return jsonP.readObj({
    required: {},
    optional: {
      "AttackId": "s",
      "ResourceArn": "s",
      "SubResources": [toSubResourceSummary],
      "StartTime": "d",
      "EndTime": "d",
      "AttackCounters": [toSummarizedCounter],
      "AttackProperties": [toAttackProperty],
      "Mitigations": [toMitigation],
    },
  }, root);
}

// refs: 1 - tags: output, named, interface
export interface SubResourceSummary {
  Type?: SubResourceType | null;
  Id?: string | null;
  AttackVectors?: SummarizedAttackVector[] | null;
  Counters?: SummarizedCounter[] | null;
}
function toSubResourceSummary(root: jsonP.JSONValue): SubResourceSummary {
  return jsonP.readObj({
    required: {},
    optional: {
      "Type": (x: jsonP.JSONValue) => cmnP.readEnum<SubResourceType>(x),
      "Id": "s",
      "AttackVectors": [toSummarizedAttackVector],
      "Counters": [toSummarizedCounter],
    },
  }, root);
}

// refs: 1 - tags: output, named, enum
export type SubResourceType =
| "IP"
| "URL"
| cmnP.UnexpectedEnumValue;

// refs: 1 - tags: output, named, interface
export interface SummarizedAttackVector {
  VectorType: string;
  VectorCounters?: SummarizedCounter[] | null;
}
function toSummarizedAttackVector(root: jsonP.JSONValue): SummarizedAttackVector {
  return jsonP.readObj({
    required: {
      "VectorType": "s",
    },
    optional: {
      "VectorCounters": [toSummarizedCounter],
    },
  }, root);
}

// refs: 3 - tags: output, named, interface
export interface SummarizedCounter {
  Name?: string | null;
  Max?: number | null;
  Average?: number | null;
  Sum?: number | null;
  N?: number | null;
  Unit?: string | null;
}
function toSummarizedCounter(root: jsonP.JSONValue): SummarizedCounter {
  return jsonP.readObj({
    required: {},
    optional: {
      "Name": "s",
      "Max": "n",
      "Average": "n",
      "Sum": "n",
      "N": "n",
      "Unit": "s",
    },
  }, root);
}

// refs: 1 - tags: output, named, interface
export interface AttackProperty {
  AttackLayer?: AttackLayer | null;
  AttackPropertyIdentifier?: AttackPropertyIdentifier | null;
  TopContributors?: Contributor[] | null;
  Unit?: Unit | null;
  Total?: number | null;
}
function toAttackProperty(root: jsonP.JSONValue): AttackProperty {
  return jsonP.readObj({
    required: {},
    optional: {
      "AttackLayer": (x: jsonP.JSONValue) => cmnP.readEnum<AttackLayer>(x),
      "AttackPropertyIdentifier": (x: jsonP.JSONValue) => cmnP.readEnum<AttackPropertyIdentifier>(x),
      "TopContributors": [toContributor],
      "Unit": (x: jsonP.JSONValue) => cmnP.readEnum<Unit>(x),
      "Total": "n",
    },
  }, root);
}

// refs: 1 - tags: output, named, enum
export type AttackLayer =
| "NETWORK"
| "APPLICATION"
| cmnP.UnexpectedEnumValue;

// refs: 1 - tags: output, named, enum
export type AttackPropertyIdentifier =
| "DESTINATION_URL"
| "REFERRER"
| "SOURCE_ASN"
| "SOURCE_COUNTRY"
| "SOURCE_IP_ADDRESS"
| "SOURCE_USER_AGENT"
| "WORDPRESS_PINGBACK_REFLECTOR"
| "WORDPRESS_PINGBACK_SOURCE"
| cmnP.UnexpectedEnumValue;

// refs: 1 - tags: output, named, interface
export interface Contributor {
  Name?: string | null;
  Value?: number | null;
}
function toContributor(root: jsonP.JSONValue): Contributor {
  return jsonP.readObj({
    required: {},
    optional: {
      "Name": "s",
      "Value": "n",
    },
  }, root);
}

// refs: 1 - tags: output, named, enum
export type Unit =
| "BITS"
| "BYTES"
| "PACKETS"
| "REQUESTS"
| cmnP.UnexpectedEnumValue;

// refs: 1 - tags: output, named, interface
export interface Mitigation {
  MitigationName?: string | null;
}
function toMitigation(root: jsonP.JSONValue): Mitigation {
  return jsonP.readObj({
    required: {},
    optional: {
      "MitigationName": "s",
    },
  }, root);
}

// refs: 2 - tags: output, named, interface
export interface Protection {
  Id?: string | null;
  Name?: string | null;
  ResourceArn?: string | null;
  HealthCheckIds?: string[] | null;
}
function toProtection(root: jsonP.JSONValue): Protection {
  return jsonP.readObj({
    required: {},
    optional: {
      "Id": "s",
      "Name": "s",
      "ResourceArn": "s",
      "HealthCheckIds": ["s"],
    },
  }, root);
}

// refs: 1 - tags: output, named, interface
export interface Subscription {
  StartTime?: Date | number | null;
  EndTime?: Date | number | null;
  TimeCommitmentInSeconds?: number | null;
  AutoRenew?: AutoRenew | null;
  Limits?: Limit[] | null;
  ProactiveEngagementStatus?: ProactiveEngagementStatus | null;
}
function toSubscription(root: jsonP.JSONValue): Subscription {
  return jsonP.readObj({
    required: {},
    optional: {
      "StartTime": "d",
      "EndTime": "d",
      "TimeCommitmentInSeconds": "n",
      "AutoRenew": (x: jsonP.JSONValue) => cmnP.readEnum<AutoRenew>(x),
      "Limits": [toLimit],
      "ProactiveEngagementStatus": (x: jsonP.JSONValue) => cmnP.readEnum<ProactiveEngagementStatus>(x),
    },
  }, root);
}

// refs: 1 - tags: output, named, interface
export interface Limit {
  Type?: string | null;
  Max?: number | null;
}
function toLimit(root: jsonP.JSONValue): Limit {
  return jsonP.readObj({
    required: {},
    optional: {
      "Type": "s",
      "Max": "n",
    },
  }, root);
}

// refs: 1 - tags: output, named, enum
export type ProactiveEngagementStatus =
| "ENABLED"
| "DISABLED"
| "PENDING"
| cmnP.UnexpectedEnumValue;

// refs: 1 - tags: output, named, enum
export type SubscriptionState =
| "ACTIVE"
| "INACTIVE"
| cmnP.UnexpectedEnumValue;

// refs: 1 - tags: output, named, interface
export interface AttackSummary {
  AttackId?: string | null;
  ResourceArn?: string | null;
  StartTime?: Date | number | null;
  EndTime?: Date | number | null;
  AttackVectors?: AttackVectorDescription[] | null;
}
function toAttackSummary(root: jsonP.JSONValue): AttackSummary {
  return jsonP.readObj({
    required: {},
    optional: {
      "AttackId": "s",
      "ResourceArn": "s",
      "StartTime": "d",
      "EndTime": "d",
      "AttackVectors": [toAttackVectorDescription],
    },
  }, root);
}

// refs: 1 - tags: output, named, interface
export interface AttackVectorDescription {
  VectorType: string;
}
function toAttackVectorDescription(root: jsonP.JSONValue): AttackVectorDescription {
  return jsonP.readObj({
    required: {
      "VectorType": "s",
    },
    optional: {},
  }, root);
}
