// Autogenerated API structures for: Amazon Timestream Query

import * as cmnP from "../../encoding/common.ts";

// refs: 1 - tags: named, input
export interface CancelQueryRequest {
  QueryId: string;
}

// refs: 1 - tags: named, input
export interface DescribeEndpointsRequest {
}

// refs: 1 - tags: named, input
export interface QueryRequest {
  QueryString: string;
  ClientToken?: string | null;
  NextToken?: string | null;
  MaxRows?: number | null;
}

// refs: 1 - tags: named, output
export interface CancelQueryResponse {
  CancellationMessage?: string | null;
}

// refs: 1 - tags: named, output
export interface DescribeEndpointsResponse {
  Endpoints: Endpoint[];
}

// refs: 1 - tags: named, output
export interface QueryResponse {
  QueryId: string;
  NextToken?: string | null;
  Rows: Row[];
  ColumnInfo: ColumnInfo[];
  QueryStatus?: QueryStatus | null;
}

// refs: 1 - tags: output, named, interface
export interface Endpoint {
  Address: string;
  CachePeriodInMinutes: number;
}

// refs: 2 - tags: output, named, interface, recursed
export interface Row {
  Data: Datum[];
}

// refs: 2 - tags: output, named, interface, recursed, recursive
export interface Datum {
  ScalarValue?: string | null;
  TimeSeriesValue?: TimeSeriesDataPoint[] | null;
  ArrayValue?: Datum[] | null;
  RowValue?: Row | null;
  NullValue?: boolean | null;
}

// refs: 1 - tags: output, named, interface, recursive
export interface TimeSeriesDataPoint {
  Time: string;
  Value: Datum;
}

// refs: 3 - tags: output, named, interface, recursed
export interface ColumnInfo {
  Name?: string | null;
  Type: Type;
}

// refs: 1 - tags: output, named, interface, recursive
export interface Type {
  ScalarType?: ScalarType | null;
  ArrayColumnInfo?: ColumnInfo | null;
  TimeSeriesMeasureValueColumnInfo?: ColumnInfo | null;
  RowColumnInfo?: ColumnInfo[] | null;
}

// refs: 1 - tags: output, named, enum
export type ScalarType =
| "VARCHAR"
| "BOOLEAN"
| "BIGINT"
| "DOUBLE"
| "TIMESTAMP"
| "DATE"
| "TIME"
| "INTERVAL_DAY_TO_SECOND"
| "INTERVAL_YEAR_TO_MONTH"
| "UNKNOWN"
| "INTEGER"
| cmnP.UnexpectedEnumValue;

// refs: 1 - tags: output, named, interface
export interface QueryStatus {
  ProgressPercentage?: number | null;
  CumulativeBytesScanned?: number | null;
  CumulativeBytesMetered?: number | null;
}
